### ISSUE TITLE
Docker Compose via Docker Hub

### ISSUE THREAD

**Issue by kanjieater** [rafyco/ytrss#174]
**Is your feature request related to a problem? Please describe.**
I'd like to run the application without having to checkout the code

**Describe the solution you'd like**
I'd like to be able to use a docker compose file to pull in a tagged docker image from a cloud container registry, like DockerHub

**Describe alternatives you've considered**
none

**Additional context**
I'm envisioning a docker compose template like what you'd see on linuxserver.io

**Comment by kanjieater** [comment]
2024-07-28 06:24:30 ytrss  | ModuleNotFoundError: No module named 'jinja2'
2024-07-28 06:25:22 ytrss  | Traceback (most recent call last):
2024-07-28 06:25:22 ytrss  |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2024-07-28 06:25:22 ytrss  |     return _run_code(code, main_globals, None,
2024-07-28 06:25:22 ytrss  |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
2024-07-28 06:25:22 ytrss  |     exec(code, run_globals)
2024-07-28 06:25:22 ytrss  |   File "/app/ytrss/__main__.py", line 4, in <module>
2024-07-28 06:25:22 ytrss  |     from ytrss.client import main
2024-07-28 06:25:22 ytrss  |   File "/app/ytrss/client.py", line 8, in <module>
2024-07-28 06:25:22 ytrss  |     from ytrss.commands import BaseCommand
2024-07-28 06:25:22 ytrss  |   File "/app/ytrss/commands/__init__.py", line 4, in <module>
2024-07-28 06:25:22 ytrss  |     from ytrss.core.managers.manager_service import default_manager_service
2024-07-28 06:25:22 ytrss  |   File "/app/ytrss/core/managers/manager_service.py", line 4, in <module>
2024-07-28 06:25:22 ytrss  |     from ytrss.core.managers.destination_manager import DestinationManager
2024-07-28 06:25:22 ytrss  |   File "/app/ytrss/core/managers/destination_manager.py", line 4, in <module>
2024-07-28 06:25:22 ytrss  |     from ytrss.core.entity.destination import Destination, DestinationError
2024-07-28 06:25:22 ytrss  |   File "/app/ytrss/core/entity/destination.py", line 8, in <module>
2024-07-28 06:25:22 ytrss  |     from ytrss.core.managers.templates_manager import TemplatesManager
2024-07-28 06:25:22 ytrss  |   File "/app/ytrss/core/managers/templates_manager.py", line 1, in <module>
2024-07-28 06:25:22 ytrss  |     from jinja2 import Environment, Template, FileSystemLoader
2024-07-28 06:25:22 ytrss  | ModuleNotFoundError: No module named 'jinja2'

Seems like even after manually building, the docker file may not be set up correctly.

**Comment by kanjieater** [comment]
If I need to make a separate issue for this, I'm happy to, but I'm trying to use this config:

```yml
---
subscriptions:
  # - name: Private playlist
  #   url: https://youtube.com/playlist?list=<playlist_id>
  #   destination: default
  - name: サイコパスおじさん
    destination: youtube
    url: https://www.youtube.com/channel/UCVkVl4K1SbgS6nzuB6uT85A
destinations:
  default:
    type: rss
    title: Youtube - podcast
    url_prefix: https://my.domain/ytdown/default
    author: youtube
    link: https://youtube.com
    desc: My favourite movies from YouTube
    img: https://www.youtube.com/yts/img/yt_1200-vfl4C3T0K.png
    path: /home/user/podcasts/default
  youtube:
    type: rss
    title: サイコパスおじさん【岡田斗司夫 切り抜き】
    url_prefix:
    author: youtube
    link: https://youtube.com
    desc: オタキングこと、岡田斗司夫さんが配信されている動画から面白い•見ごたえのあるシーンや考察部分を切り抜いてフルテロップ（字幕）で分かりやすくコンパクトに編集していきます。
    img: https://yt3.googleusercontent.com/YXznxdW-y_OUet1TcBbtGXyz9Yf_xqJBNwlSrILzHAd5eU_KfXRRWGQtaC-ihDnRKipT7i6G=s900-c-k-c0x00ffffff-no-rj
    path: /downloads/jpodcasts/サイコパスおじさん

```

I'm a little confused if the `destinations` are intended to be reusable? Or should i be defining a new desitnation for every single subscription?
